# Generated by Django 3.0.5 on 2020-04-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='isfav',
            field=models.BooleanField(default=False),
        ),
    ]
